### ISSUE TITLE
Please merge it to Amazon

### ISSUE THREAD

**Issue by Nenino2** [Andrews2004000/FrontendProva#1]
Ti consiglio di non utilizzare repository diverse ma solo Amazon, con diverse branch all'interno per fare le prove.

**Comment by Nenino2** [comment]
@Andrews2004000

**Comment by Andrews2004000** [comment]
Wow

**Comment by Nenino2** [comment]
Se clicchi "Close Issue" puoi segnalare come bug risolto

**Comment by Nenino2** [comment]
Posso anche inviare dei suggerimenti del codice:
`<p>Ciao</p>`

**Comment by Andrews2004000** [comment]
troppo utile

**Comment by Nenino2** [comment]
Wow

> * [ ]  Prima cosa da fare
> * [ ]  Seconda cosa da fare
> * [ ]  Ultima cosa da fare

**Comment by Andrews2004000** [comment]
`Hi i'm testing some commands`

**Comment by Andrews2004000** [comment]
<img width="1440" alt="Schermata 2020-06-05 alle 20 54 15" src="https://user-images.githubusercontent.com/57257154/83915647-f8795400-a773-11ea-9a61-c124d7fc7aa2.png">
Testing

**Comment by Andrews2004000** [comment]
#Referencing to a Issue

**Comment by Nenino2** [comment]
In questa commit si sono aggiunte cose
8f2387390e1bf2ed951d529bf7d8137d4c038e77

**Comment by Nenino2** [comment]
Ho fatto il merge con amazon. Chiudo l'issue
